MAINT: Update versions in all req files
ansys/pyansys-workflows pull request #43
Opened 2024-12-13 17:46 UTC by dipinknair

dependabot pip update is currently only for docs hence this has to be done manually.

2024-12-13 19:45 UTC, dipinknair commented on .github/dependabot.yml
> +       build-deps:
```suggestion
       wf-deps:
```

2024-12-13 21:50 UTC, MaxJPRey approved these changes

2024-12-13 21:52 UTC, MaxJPRey requested changes
Was this expected @RobPasMue ? Maybe for the versioning compatibility, I can't remember.

2024-12-15 09:06 UTC, RobPasMue requested changes
@dipinknair please close this PR and do not merge. This is on purpose. Certain libraries only have a 1-to-1 compatibility and thus we leave reqs files separated for all server versions. If your library (PyMechanical) is compatible and you want to bump it, please go ahead... But do not assume all of them can be upgraded.

2024-12-16 14:29 UTC, closed without merging